use super::*;

pub(super) fn registry() -> Vec<ShortcutBinding> {
    use ShortcutGuard::*;
    use ShortcutModifiers as Mods;
    use ShortcutScope::*;

    let categories = [
        (egui::Key::Num1, AtomCategory::Protein, "Select Protein"),
        (
            egui::Key::Num2,
            AtomCategory::NucleicAcid,
            "Select Nucleic Acid",
        ),
        (
            egui::Key::Num3,
            AtomCategory::Carbohydrate,
            "Select Carbohydrate",
        ),
        (egui::Key::Num4, AtomCategory::Ligand, "Select Ligand"),
        (egui::Key::Num5, AtomCategory::Solvent, "Select Solvent"),
        (egui::Key::Num6, AtomCategory::Ion, "Select Ion"),
    ];

    let mut bindings = vec![
        bind_action(
            "file.new_project",
            Global,
            egui::Key::N,
            Mods::MOD,
            AppAction::CreateProject,
            "Create Project",
            Always,
        ),
        bind_action(
            "file.open_project",
            Global,
            egui::Key::O,
            Mods::MOD,
            AppAction::OpenProject,
            "Open Project",
            Always,
        ),
        bind_action(
            "file.open_file",
            Global,
            egui::Key::O,
            Mods::MOD_SHIFT,
            AppAction::OpenFile,
            "Open File",
            Always,
        ),
        bind_action(
            "file.save",
            Global,
            egui::Key::S,
            Mods::MOD,
            AppAction::Save,
            "Save",
            HasActiveEntry,
        ),
        bind_action(
            "file.save_as",
            Global,
            egui::Key::S,
            Mods::MOD_SHIFT,
            AppAction::SaveAs,
            "Save As",
            HasActiveEntry,
        ),
        bind_action(
            "file.save_project",
            Global,
            egui::Key::S,
            Mods::MOD_ALT,
            AppAction::SaveProject,
            "Save Project",
            ProjectWorkspace,
        ),
        bind_ui(
            "app.settings",
            Global,
            egui::Key::Comma,
            Mods::MOD,
            ShortcutCommand::ToggleSettings,
            "Settings",
            Always,
        ),
        bind_action(
            "edit.undo",
            Global,
            egui::Key::Z,
            Mods::MOD,
            AppAction::Undo,
            "Undo",
            HistoryNavigation,
        ),
        bind_action(
            "edit.redo",
            Global,
            egui::Key::Y,
            Mods::MOD,
            AppAction::Redo,
            "Redo",
            HistoryNavigation,
        ),
        bind_action(
            "edit.redo_alt",
            Global,
            egui::Key::Z,
            Mods::MOD_SHIFT,
            AppAction::Redo,
            "Redo",
            HistoryNavigation,
        ),
        bind_action(
            "selection.all",
            Selection,
            egui::Key::A,
            Mods::MOD,
            AppAction::SelectAll,
            "Select All",
            HasActiveEntry,
        ),
        bind_action(
            "selection.clear",
            Selection,
            egui::Key::A,
            Mods::MOD_SHIFT,
            AppAction::ClearSelection,
            "Clear Selection",
            HasActiveEntry,
        ),
        bind_action(
            "selection.invert",
            Selection,
            egui::Key::I,
            Mods::MOD,
            AppAction::InvertSelection,
            "Invert Selection",
            HasActiveEntry,
        ),
        bind_action(
            "view.primary_sidebar",
            Workbench,
            egui::Key::B,
            Mods::MOD,
            AppAction::TogglePrimarySidebar,
            "Primary Side Bar",
            Always,
        ),
        bind_ui(
            "view.primary.entries",
            Workbench,
            egui::Key::Num1,
            Mods::MOD,
            ShortcutCommand::SetPrimaryView(PrimaryView::EntryList),
            "Entry List",
            Always,
        ),
        bind_ui(
            "view.primary.tasks",
            Workbench,
            egui::Key::Num2,
            Mods::MOD,
            ShortcutCommand::SetPrimaryView(PrimaryView::Tasks),
            "Tasks",
            Always,
        ),
        bind_ui(
            "view.primary.style",
            Workbench,
            egui::Key::Num3,
            Mods::MOD,
            ShortcutCommand::SetPrimaryView(PrimaryView::Style),
            "Style",
            Always,
        ),
        bind_ui(
            "view.search",
            Workbench,
            egui::Key::F,
            Mods::MOD,
            ShortcutCommand::OpenPrimarySearch,
            "Search",
            PrimarySidebarVisible,
        ),
        bind_action(
            "view.panel",
            Workbench,
            egui::Key::J,
            Mods::MOD,
            AppAction::ToggleDockArea(DockArea::Bottom),
            "Panel",
            Always,
        ),
        bind_action(
            "view.secondary_sidebar",
            Workbench,
            egui::Key::J,
            Mods::MOD_SHIFT,
            AppAction::ToggleDockArea(DockArea::Right),
            "Secondary Side Bar",
            Always,
        ),
        bind_ui(
            "view.console",
            Workbench,
            egui::Key::Backtick,
            Mods::MOD,
            ShortcutCommand::RevealStaticView(StaticView::Console),
            "Console",
            Always,
        ),
        bind_ui(
            "view.task_monitor",
            Workbench,
            egui::Key::T,
            Mods::MOD_SHIFT,
            ShortcutCommand::RevealStaticView(StaticView::TaskMonitor),
            "Task Monitor",
            Always,
        ),
        bind_action(
            "view.reset_layout",
            Workbench,
            egui::Key::L,
            Mods::MOD_SHIFT,
            AppAction::ResetWorkbenchLayout,
            "Reset Workbench Layout",
            Always,
        ),
        bind_action(
            "style.ball_and_stick",
            Selection,
            egui::Key::V,
            Mods::NONE,
            AppAction::SetSelectionStyle(AtomStyle::BallAndStick),
            "Ball-and-stick",
            HasActiveEntry,
        ),
        bind_action(
            "style.wireframe",
            Selection,
            egui::Key::W,
            Mods::NONE,
            AppAction::SetSelectionStyle(AtomStyle::Wireframe),
            "Wireframe",
            HasActiveEntry,
        ),
        bind_action(
            "style.sphere",
            Selection,
            egui::Key::S,
            Mods::NONE,
            AppAction::SetSelectionStyle(AtomStyle::Sphere),
            "Space-filling",
            HasActiveEntry,
        ),
        bind_action(
            "style.hide_selection",
            Selection,
            egui::Key::H,
            Mods::NONE,
            AppAction::SetSelectionVisibility(VisibilityCommand::Hide),
            "Hide Selection",
            HasSelection,
        ),
        bind_action(
            "style.show_selection",
            Selection,
            egui::Key::H,
            Mods::SHIFT,
            AppAction::SetSelectionVisibility(VisibilityCommand::Show),
            "Show Selection",
            HasActiveEntry,
        ),
        bind_action(
            "style.atom_labels",
            Selection,
            egui::Key::L,
            Mods::NONE,
            AppAction::ToggleAtomLabels,
            "Show Atom Labels",
            HasActiveEntry,
        ),
        bind_ui(
            "viewport.reset_camera",
            Viewport,
            egui::Key::R,
            Mods::NONE,
            ShortcutCommand::ResetViewportCamera,
            "Reset View",
            HasActiveEntry,
        ),
        bind_ui(
            "viewport.zoom_in",
            Viewport,
            egui::Key::Plus,
            Mods::NONE,
            ShortcutCommand::ZoomViewport(0.1),
            "Zoom In",
            HasActiveEntry,
        ),
        bind_ui(
            "viewport.zoom_in_equals",
            Viewport,
            egui::Key::Equals,
            Mods::NONE,
            ShortcutCommand::ZoomViewport(0.1),
            "Zoom In",
            HasActiveEntry,
        ),
        bind_ui(
            "viewport.zoom_out",
            Viewport,
            egui::Key::Minus,
            Mods::NONE,
            ShortcutCommand::ZoomViewport(-0.1),
            "Zoom Out",
            HasActiveEntry,
        ),
        bind_action(
            "trajectory.toggle_play",
            Trajectory,
            egui::Key::Space,
            Mods::NONE,
            AppAction::ToggleTrajectoryPlay,
            "Play/Pause Trajectory",
            TrajectoryLoaded,
        ),
        bind_ui(
            "trajectory.load_default",
            Trajectory,
            egui::Key::Space,
            Mods::SHIFT,
            ShortcutCommand::LoadDefaultTrajectory,
            "Load Trajectory",
            ActiveMdEntryWithTrajectory,
        ),
        bind_ui(
            "app.escape",
            Modal,
            egui::Key::Escape,
            Mods::NONE,
            ShortcutCommand::Escape,
            "Escape",
            Always,
        ),
    ];

    for (key, category, label) in categories {
        bindings.push(bind_action(
            category_shortcut_id(category),
            Selection,
            key,
            Mods::ALT,
            AppAction::SelectCategory(category),
            label,
            HasActiveEntry,
        ));
    }
    bindings
}

fn bind_action(
    id: &'static str,
    scope: ShortcutScope,
    key: egui::Key,
    modifiers: ShortcutModifiers,
    action: AppAction,
    label: &'static str,
    when: ShortcutGuard,
) -> ShortcutBinding {
    ShortcutBinding::new(
        id,
        scope,
        key,
        modifiers,
        ShortcutCommand::Action(action),
        label,
        when,
    )
}

fn bind_ui(
    id: &'static str,
    scope: ShortcutScope,
    key: egui::Key,
    modifiers: ShortcutModifiers,
    command: ShortcutCommand,
    label: &'static str,
    when: ShortcutGuard,
) -> ShortcutBinding {
    ShortcutBinding::new(id, scope, key, modifiers, command, label, when)
}

fn category_shortcut_id(category: AtomCategory) -> &'static str {
    match category {
        AtomCategory::Protein => "selection.category.protein",
        AtomCategory::NucleicAcid => "selection.category.nucleic_acid",
        AtomCategory::Carbohydrate => "selection.category.carbohydrate",
        AtomCategory::Ligand => "selection.category.ligand",
        AtomCategory::Solvent => "selection.category.solvent",
        AtomCategory::Ion => "selection.category.ion",
        AtomCategory::Other => "selection.category.other",
    }
}
